### ISSUE TITLE
Can't set the font in VS Code running on Windows 11

### ISSUE THREAD

**Issue by kossnocorp** [evilmartians/mono#10]
I tried different combinations, including `Martians Mono`, `"Martians Mono"`, `MartiansMono` and even the full name `Martian Mono Std Lt`, but no luck.

I'm not sure if I don't understand how font names work or if it's a font issue, either way, it's worth adding this to docs since the mono font will be used mainly by developers.

![image](https://user-images.githubusercontent.com/52201/180418114-30aac5a6-775b-47fc-8140-f1d51370c206.png)

Btw, thank you for your amazing work.

**Comment by alexeyten** [comment]
What version did you install?
What OS?
Have you tried `Martian Mono` (not Martian**S**)?

**Comment by alexeyten** [comment]
By version I mean OTF, TTF, variable?
Does it work in other applications?
Have you restarted VS Code or OS after installation?

Also you could check [this instruction](https://github.com/tonsky/FiraCode/wiki/Installing#windows) to be sure that you've property installed the font.

**Comment by kossnocorp** [comment]
Thank you for your help. After "unblocking" all the typefaces, setting `Martian Mono Std Lt` did work out.

![image](https://user-images.githubusercontent.com/52201/180589176-46dcfde6-b418-41fa-bb3e-22d3add31c50.png)

I think it's worth mentioning in the docs.

**Comment by romashamin** [comment]
Thank you, @alexeyten!

It seems like I can close this issue.
