### ISSUE TITLE
THE BEST MONO FONT FOR PROGRAMMING!!!!!!!

### ISSUE THREAD

**Issue by schwrzstrbn** [evilmartians/mono#13]

**Comment by alexmyczko** [comment]
personally i like https://github.com/blobject/agave better for terminal and programming...

**Comment by schwrzstrbn** [comment]
> personally i like https://github.com/blobject/agave better for terminal and programming...

looks good.

**Comment by romashamin** [comment]
@schwrzstrbn thank you very much!
