### ISSUE TITLE
Hello, will consider support nerdfont icon?

### ISSUE THREAD

**Issue by jinfagang** [evilmartians/mono#14]
I really like martian mano font, after using this, all font looks uncomfortable to me.

But as a programer, I like vim, martian don't have icon support is really a pity, will it consider support?

<img width="76" alt="image" src="https://user-images.githubusercontent.com/21303438/191505937-90bfadd2-dfe1-4444-8d27-043f8919fed1.png">

**Comment by romashamin** [comment]
Duplicates #5.
