### ISSUE TITLE
Martian Mono isn’t being detected as a monospaced font

### ISSUE THREAD

**Issue by kalashnikovisme** [evilmartians/mono#16]
User can set only mono fonts in Gnome Terminal on Ubuntu 22.04 by default, and Gnome Terminal does not detect MartianMono as monospace font for some reason.

You can choose MartianMono font as terminal font with this command

```
dconf write /org/gnome/terminal/legacy/profiles:/:TERMINAL_PROFILE_ID/font  "'<font name> <font size>'"
```
for example

```
dconf write /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font  "'MartianMono sWd xLt 12'"
```

Also, we can see that `Font Manager` detects MartianMono as `proportional`, not `monospace`

![Screenshot from 2022-10-23 06-17-18](https://user-images.githubusercontent.com/2001025/197369898-0f6cf513-8f3d-40f8-8825-a27b5c4ebb77.png)

**Comment by bitimp** [comment]
If I haven't missed anything, then `spacing` property is not set in the font. This property must be set to 100.
How to check:

`fc-scan /<path>/<to>/<font>.ttf`

Example:
<pre>$ fc-scan /usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf
Pattern has 25 elts (size 32)
        family: "Ubuntu Mono"(s)
        familylang: "en"(s)
        style: "Regular"(s)
        stylelang: "en"(s)
        fullname: "Ubuntu Mono"(s)
        fullnamelang: "en"(s)
        slant: 0(i)(s)
        weight: 80(f)(s)
        width: 100(f)(s)
        spacing: 100(i)(s)
        foundry: "DAMA"(s)
        file: "/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf"(s)
        index: 0(i)(s)
        outline: True(s)
        scalable: True(s)
        ...
</pre>

If you run `fc-list :spacing=100 fullname spacing` then MartianMono will not be in the output.

**Comment by romashamin** [comment]
The Glyphs app forum topic related to the issue (it’s for me mostly):
https://forum.glyphsapp.com/t/isfixedpitch-to-disable-metrics-adjustment

**Comment by romashamin** [comment]
Related issue: https://github.com/google/fonts/issues/225

**Comment by romashamin** [comment]
@kalashnikovisme try please these updated fonts, all of them have `isFixedPitch = true`.

https://github.com/evilmartians/mono/tree/main/fonts

Did it fix the issue?

**Comment by kalashnikovisme** [comment]
@romashamin sorry for the delay, I missed this comment.

I've tried new files, unfortunately issue still exists :slightly_frowning_face:

**Comment by kalashnikovisme** [comment]
@romashamin checked one more time with v1.0. Everything is ok now! Thanks!
