### ISSUE TITLE
Странные значения weight и style в ttf

### ISSUE THREAD

**Issue by alexeyten** [evilmartians/mono#2]
Вот такие веса показывает `fc-scan` (fontconfig) в Ubuntu
```
$ fc-scan --format '%{file}\t%{weight}\t%{style}\n' MartianMono-Std*.ttf
MartianMono-StdBd.ttf	200	Std Bd,Bold
MartianMono-StdLt.ttf	80	Std Lt,Regular
MartianMono-StdMd.ttf	80	Std Md,Regular
MartianMono-StdRg.ttf	80	Std Rg,Regular
MartianMono-StdTh.ttf	0	Std Th,Regular
MartianMono-StdxBd.ttf	205	Std xBd,Regular
MartianMono-StdxLt.ttf	80	Std xLt,Regular
```

По [документации](https://linux.die.net/man/5/fonts-conf) я бы ожидал для
Lt — 50
Md — 100
xLt — 40

Ну и style у всех почему-то `Regular`.

**Comment by romashamin** [comment]
Поресёрчил проблему.

Glyphs, как будто бы, действительно не всегда правильно задаёт параметр usWeightClass:
![image](https://user-images.githubusercontent.com/1148914/161382352-80d28de7-98eb-43ca-b8ee-434d5c21bfe1.jpg)

Я уже написал о проблеме разработчику. Разбираемся.

**Comment by romashamin** [comment]
> По [документации](https://linux.die.net/man/5/fonts-conf) я бы ожидал

Не понимаю откуда берутся 50 для Light, 80 для Regular и 100 для Medium.

В спецификациях [OpenType](https://docs.microsoft.com/en-gb/typography/opentype/spec/os2#usweightclass) и [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#common_weight_name_mapping) для тех же классов предполагаются 300, 400 и 500.

**Comment by alexeyten** [comment]
Возможно freetype их как-то сам матчит. Во всяком случае для остальных файлов он показывает правильные значения.

**Comment by romashamin** [comment]
Проблема обнаружена, со следующим апдейтом будет фикс.

**Comment by alexeyten** [comment]
А значения `style` тоже поправятся?

**Comment by romashamin** [comment]
FIxed in 0.9.1.
