### ISSUE TITLE
Can't find the source of the font?

### ISSUE THREAD

**Issue by alexmyczko** [evilmartians/mono#3]
Will that follow at some later point?

**Comment by raphaelbastide** [comment]
@romashamin Maybe removing the libre license until the source code is public, could be more clear for visitors of the projects? Right now it seems the font is open source but it’s not.

**Comment by alexmyczko** [comment]
It is not much disturbing me, as when the plan is that license it will be so sooner or later

**Comment by romashamin** [comment]
> Maybe removing the libre license until the source code is public, could be more clear for visitors of the projects?

@raphaelbastide in this case, I’d have to change the OFL with something else—I can’t publish the font without any license, right? I decided it’s more useful to spend time improving the font—adding languages, etc.—than searching for a temporary license.

**Comment by raphaelbastide** [comment]
> @raphaelbastide in this case, I’d have to change the OFL with something else—I can’t publish the font without any license, right? I decided it’s more useful to spend time improving the font—adding languages, etc.—than searching for a temporary license.

I can understand the choice of not distributing the source code, and of course focusing on drawing is a priority, however I don’t understand the use of Github if there is no source code available, as git is made to document, share, study source code, not only compiled files.
Anyway, if you just remove the OFL license, the projects falls in *all rights are reserved*, if I understand correctly how Github works. In this case, I can’t do anything with your source code, which is already the case. Maybe this is the good temporary solution until the source code is public?
Just for some context: I just discovered the font and it looks great -  I use libre software and fonts only for my practice and education things. I can’t really use and share Martian Mono right now, that is why I am a bit frustrated.

**Comment by davelab6** [comment]
Many fonts are liberated using OFL without sources, because the compilation process for fonts isn't as destructive as it is for program code. I suggest keeping the OFL, and adding your Glyphsapp file when you are comfortable. No need to remove the license making it entirely non libre, or use any other license temporarily.

**Comment by romashamin** [comment]
Fixed in 0.9.1.
