### ISSUE TITLE
Setting `editor.fontVariations` in VSCode under Linux

### ISSUE THREAD

**Issue by lakshits11** [evilmartians/mono#30]
Hey!
Can you provide more info on how to use fontVariations settings and to use it, which font type to install (OTF/TTF/Variable) on Windows and for linux?

**Comment by lakshits11** [comment]
Also I installed variable font on arch linux and unable to replicate te width and font weight changes using `editor.fontVariations` in vscode as described in README of this repo

**Comment by alexeyten** [comment]
Not sure what you expect from `'ital' 0.5`, but this font does not (yet) have italic style.

**Comment by lakshits11** [comment]
ok but it is also not working in vscode:
```jsonc
// settings.json
{
    "editor.fontFamily": "Martian Mono",
    "editor.fontVariations": "'wdth' 87.5, 'wght' 450",
}
```

**Comment by romashamin** [comment]
> which font type to install (OTF/TTF/Variable) on Windows and for linux?

Prefer variable `ttf` or static `otf` font files for macOS, and `ttf` for Windows. Use `woff2` and `woff` for web development.

Some Linux distributives do support the `ttf` font format while others do not. Please, read the documentation for your distributive.

**Comment by romashamin** [comment]
I just checked the following setting in VSCode under macOS:
```
{
    "editor.fontFamily": "'Martian Mono', Menlo, monospace",
    "editor.fontVariations": "'wdth' 75, 'wght' 800",
}
```

Everything seems fine:
![image (16)](https://github.com/evilmartians/mono/assets/1148914/32d15423-766c-44e0-8b60-c221d6007f09)

I asked some friends with Linuxes to check. Let’s wait for their feedback.

**Comment by lakshits11** [comment]
Yeah I think it is neither working on Linux nor on WIndows. I have both. Tried on both.

**Comment by Envek** [comment]
@lakshits11, on Arch you can install variable font from [ttf-martian-mono-variable](https://aur.archlinux.org/packages/ttf-martian-mono-variable) AUR package:

```sh
yay ttf-martian-mono-variable
```

However, `editor.fontVariations` doesn't seem to work for me either (I'm on Manjaro Linux).

It seems that underlying Chromium lacks support for it at the moment (see [Can I Use](https://caniuse.com/mdn-css_at-rules_font-face_font-variation-settings) and [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variation-settings)), so, probably we only can to wait for the support to be implemented (not sure why it is working on MacOS though).

**Comment by romashamin** [comment]
It seems like VSCode supports neither `editor.fontVariations` nor `editor.fontStretch`.

Install static Martin Mono.

Consider [creating an issue](https://github.com/microsoft/vscode/issues) in the VSCode repo.
