### ISSUE TITLE
[Feature Request]Plan to provide the nerd icons patched fonts?

### ISSUE THREAD

**Issue by xfyuan** [evilmartians/mono#5]
First thanks for the great mono font!

I would like to know is there any plan to patched the nerd icons with it?
[nerd-font site](https://github.com/ryanoasis/nerd-fonts) 

Because many developers use that style font now, just like me. So I think it should be a better way to make Martian Mono font to be more popular.

**Comment by caraya** [comment]
If you will use mono as a web font you want it to be as lean as possible. I would rather not have the font include icons

**Comment by xfyuan** [comment]
> If you will use mono as a web font you want it to be as lean as possible. I would rather not have the font include icons

Oh, my advice is not for web font usage, but for the desktop App usage like iTerm2.

**Comment by caraya** [comment]
> > If you will use mono as a web font you want it to be as lean as possible. I would rather not have the font include icons
> 
> Oh, my advice is not for web font usage, but for the desktop App usage like iTerm2.

I get that but right now since there is one version of the font released it would be an all-or-nothing proposition. Unless the author releases more than one version of the font where we can all be happy with what we want

**Comment by romashamin** [comment]
> I would like to know is there any plan to patched the nerd icons with it?

@xfyuan yes, it is. I already had a conversation with someone from Nerd Fonts project. We agreed that it would make more sense after the version 1.0 release.

**Comment by jinfagang** [comment]
@romashamin  Hi, it's a very nice feature. Does there any time scheduled for 1.0 release?

BTW, for the above someone said Martin font should be small as possible for web font usage, I agreed with that, but nerd font is not a only font for Martain font, it can be an option for it as many other Nerd font.

**Comment by romashamin** [comment]
> Does there any time scheduled for 1.0 release?

Unfortunately, there’s not.

The roadmap to version 1.0 right now looks like this:
- the Cyrillic script,
- some fixes,
- a big journey called “Italics”.

@jinfagang

**Comment by romashamin** [comment]
https://github.com/ryanoasis/nerd-fonts/pull/1092

**Comment by romashamin** [comment]
https://www.nerdfonts.com/font-downloads

Thx to @skryukov 🙌
