### ISSUE TITLE
diacrical marks

### ISSUE THREAD

**Issue by CastixGitHub** [evilmartians/mono#7]
accents and so on... [ugly example](http://gossipsloth.com/contentImages/Smaller-6f0595f88cddd33369f2291b2dac4540.jpeg)
(ok, i see you said you provide just basic latin currently)

**Comment by romashamin** [comment]
@CastixGitHub the following characters with diacritics are expected in the upcoming version 0.9.1.

![martian-mono-0 9 1rc-2@2x](https://user-images.githubusercontent.com/1148914/177173189-f2dc257d-0ab2-44ce-9f3d-318fe6125cc9.png)

**Comment by romashamin** [comment]
Fixed in 0.9.1.
